var entry = {
	"Size": "Small",
	"Type": "sleepingmat",
	"Brand": "Therm-a-Rest",
	"Model": "NeoAir® XLite™",
	"Image": "https://www.thermarest.com/dw/image/v2/BDJM_PRD/on/demandware.static/-…",
	"ManufacturerURL": "https://www.thermarest.com/fr/produits/matelas/fr/matelas/fast-and-lig…",
	"SKU": "13211",
	"Color": "Lemon Curry",
	"R-Value": "4.2",
	"Weight (Standard)": "8.3 oz",
	"Weight (Metric)": "240 g",
	"Width (Standard)": "20 in",
	"Width (Metric)": "51 cm",
	"Length (Standard)": "47 in",
	"Length (Metric)": "119 cm",
	"Height (Standard)": "2.5 in",
	"Height (Metric)": "6.4 cm",
	"Thickness (Standard)": "2.5 in",
	"Thickness (Metric)": "6.4 cm",
	"Packed dimension (Standard)": "9 in x 3.5 in",
	"Packed dimension (Metric)": "23 cm x 9 cm",
	"Top fabric type": "30D rip HT Nylon",
	"Bottom fabric type": "30D rip HT Nylon",
	"What's Included": "Pump sack, stuff sack and repair kit"
}